{% set name = "qiskit-machine-learning" %}
{% set version = "0.8.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 8520df316c597a0aac7eb13b839ad43827c4350cb55332f401aed0c345212509

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - qiskit >=1.0,<2.0
    - dill >=0.3.4
    - numpy >=2.0
    - psutil >=5
    - python >={{ python_min }}
    - scikit-learn >=1.2
    - scipy >=1.4
    - setuptools >=40.1

test:
  imports:
    - qiskit_machine_learning
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/qiskit-community/qiskit-machine-learning
  summary: 'Qiskit Machine Learning: A library of quantum computing machine learning experiments'
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - wshanks
    - BastianZim
