{% set name = "qiskit-machine-learning" %}
{% set version = "0.8.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 4bdac19aab6e5596aee34b2f5ac2697bef594117d505cd050935b8596b1bc9b4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools
  run:
    - qiskit >=1.0
    - dill >=0.3.4
    - fastdtw
    - numpy >=1.17
    - psutil >=5
    - python >=3.9
    - scikit-learn >=1.2
    - scipy >=1.4
    - setuptools >=40.1

test:
  imports:
    - qiskit_machine_learning
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/qiskit-community/qiskit-machine-learning
  summary: 'Qiskit Machine Learning: A library of quantum computing machine learning experiments'
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - wshanks
    - BastianZim
